// petra-gen.mjs — regenerates js/data/petra.js from the casual-tourist golden scenario
// (Living-World W4, docs/08-living-world.md point 10 "Petra, the Pace Ghost").
// Run: node js/dev/petra-gen.mjs
//
// REGENERATE with `node js/dev/petra-gen.mjs` whenever the casual golden re-pins (selftest
// [109]/[112]/[113]/[114] all pin casual-tourist's islandAt to 76800s ±1200 — if a balance wave
// moves that pin, Petra's baked itinerary drifts out of tolerance and validatePetra() (in the
// generated file) starts failing until this is re-run).
//
// Imports ONLY the existing demo/scenario tooling (never edits demo.mjs, per house rule) — Petra
// is display-only data, not a new simulation.
import { runScenario } from './demo.mjs';
import { getScenario } from './scenarios.mjs';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// One wry line — Petra is a relentlessly average package tourist: same brochure, same pace,
// every single life (she "re-books the same package every life", per the plan — lean into it).
const FLAVOR = 'Books the same all-inclusive every single life, double-checks the brochure, and somehow is still exactly on schedule.';

const sc = getScenario('casual-tourist');
const r = runScenario(sc, { maxHours: 40 });   // default dt/snapshotSec/cadence (the scenario's own 1200s cadence)

const tierTimes = {};
const beatTimes = {};
for (const e of r.events) {
  if (e.type === 'tier' && tierTimes[e.tier] === undefined) tierTimes[e.tier] = e.t;
  if (e.type === 'beat' && beatTimes[e.beat] === undefined) beatTimes[e.beat] = e.t;
}

if (r.islandAt === null) {
  console.error('petra-gen: casual-tourist did not reach the island within the 40h horizon — aborting (nothing written)');
  process.exit(1);
}

const HEADER = [
  '// data/petra.js — GENERATED by js/dev/petra-gen.mjs. Do not hand-edit.',
  '// REGENERATE with `node js/dev/petra-gen.mjs` whenever the casual golden re-pins.',
  '//',
  '// Petra, the Pace Ghost (Living-World W4, docs/08-living-world.md point 10): a rival NPC whose',
  '// itinerary is the casual-tourist golden curve (js/dev/scenarios.mjs), baked as flat data.',
  '// DISPLAY-ONLY — never read by any engine.js/math.js income path (see docs/08\'s neutrality',
  '// class table: a "ghost" is display-only, same bucket as weather/postcards). tierTimes/beatTimes',
  '// map an accommodation tier / story beat id -> the game-second Petra\'s OWN casual-tourist run',
  '// first reached it; islandAt is her tier-20 (Private Island) arrival time.',
].join('\n');

const BODY = [
  'export const PETRA = {',
  "  name: 'Petra',",
  `  flavor: ${JSON.stringify(FLAVOR)},`,
  `  tierTimes: ${JSON.stringify(tierTimes, null, 2)},`,
  `  beatTimes: ${JSON.stringify(beatTimes, null, 2)},`,
  `  islandAt: ${r.islandAt},`,
  '};',
].join('\n');

const VALIDATOR = [
  '',
  '// validatePetra(): a pin-consistency guard, not a balance assertion — (a) both time maps are',
  '// monotone non-decreasing as their key (tier/beat number) increases, since Petra only ever moves',
  '// forward through her own itinerary; (b) islandAt sits within the SAME +/-1200s tolerance',
  '// selftest pins the casual-tourist golden to (76800s -- see selftest [109]/[112]/[113]/[114]), so',
  '// a stale Petra (baked before a balance re-pin) fails loudly instead of quietly lying to players',
  '// about their pace. Throws loudly on failure -- called from dev/harness.mjs and dev/selftest.mjs.',
  'export function validatePetra() {',
  '  const errors = [];',
  '  const CASUAL_ISLAND_PIN = 76800, CASUAL_ISLAND_TOL = 1200;',
  '  const monotone = (map, label) => {',
  '    const keys = Object.keys(map).map(Number).sort((a, b) => a - b);',
  '    let last = -Infinity;',
  '    for (const k of keys) {',
  '      const t = map[k];',
  "      if (typeof t !== 'number' || !Number.isFinite(t) || t < 0) errors.push(`petra.${label}[${k}] must be a finite number >= 0 (got ${t})`);",
  '      else if (t < last) errors.push(`petra.${label} is not monotone at key ${k} (${t} < ${last})`);',
  '      last = t;',
  '    }',
  '    if (!keys.length) errors.push(`petra.${label} must not be empty`);',
  '  };',
  "  monotone(PETRA.tierTimes, 'tierTimes');",
  "  monotone(PETRA.beatTimes, 'beatTimes');",
  "  if (typeof PETRA.islandAt !== 'number' || !(PETRA.islandAt > 0)) errors.push('petra.islandAt must be a positive number');",
  '  else if (Math.abs(PETRA.islandAt - CASUAL_ISLAND_PIN) > CASUAL_ISLAND_TOL) {',
  '    errors.push(`petra.islandAt (${PETRA.islandAt}) has drifted outside the casual-tourist pin (${CASUAL_ISLAND_PIN} +/-${CASUAL_ISLAND_TOL}) -- regenerate with node js/dev/petra-gen.mjs`);',
  '  }',
  "  if (typeof PETRA.name !== 'string' || !PETRA.name) errors.push('petra.name must be a non-empty string');",
  "  if (typeof PETRA.flavor !== 'string' || !PETRA.flavor) errors.push('petra.flavor must be a non-empty string');",
  "  if (errors.length) throw new Error('validatePetra() failed:\\n' + errors.join('\\n'));",
  '  return true;',
  '}',
  '',
].join('\n');

const out = HEADER + '\n' + BODY + '\n' + VALIDATOR;

const outPath = path.join(path.dirname(fileURLToPath(import.meta.url)), '../data/petra.js');
writeFileSync(outPath, out);
console.log(`wrote js/data/petra.js -- islandAt ${r.islandAt}s (${Object.keys(tierTimes).length} tiers, ${Object.keys(beatTimes).length} beats)`);
